In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.duplicated().sum()

0

In [6]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [7]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [8]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [9]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace= True)

In [10]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [11]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first= True)

In [12]:
X = df.drop(columns=['Exited'])
Y = df['Exited']

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size= 0.2, random_state= 1)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [17]:
x_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()

In [20]:
model.add(Dense(3, activation = 'sigmoid', input_dim = 11))
model.add(Dense(1, activation = 'sigmoid'))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 36        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(loss= 'binary_crossentropy', optimizer= 'Adam')

In [23]:
model.fit(x_train_scaled, y_train, epochs= 10)

Epoch 1/10
250/250 [==============================] - 1s 3ms/step - loss: 0.8526
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.6443
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.5416
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4931
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4699
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4574
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4494
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4437
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4392
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4358


In [24]:
model.layers[0].get_weights()

[array([[-0.3300917 , -0.20664944, -0.06813426],
        [ 1.5336329 ,  0.7572079 , -1.4373933 ],
        [-0.05644245,  0.19863041,  0.08158728],
        [ 0.34454155, -0.19256876, -0.4493317 ],
        [-0.13441533,  0.05406672,  0.02271616],
        [-0.27792865,  0.10058171, -0.03776173],
        [-0.25912052, -1.002211  ,  0.76750684],
        [-0.2880905 ,  0.28636184, -0.13931336],
        [ 0.34442607,  0.78333485, -0.48760644],
        [ 0.18939866, -0.2502564 ,  0.06637157],
        [-0.3077379 , -0.5610432 ,  0.43971038]], dtype=float32),
 array([-0.5807065 , -0.58879346,  0.97617924], dtype=float32)]

In [25]:
model.layers[1].get_weights()

[array([[ 0.6223845 ],
        [ 0.39319092],
        [-1.4897245 ]], dtype=float32),
 array([-0.85672927], dtype=float32)]

In [26]:
model.predict(x_test_scaled)

63/63 [==============================] - 0s 4ms/step


array([[0.13815685],
       [0.15258762],
       [0.156328  ],
       ...,
       [0.09944613],
       [0.1557586 ],
       [0.36401957]], dtype=float32)

In [27]:
y_log = model.predict(x_test_scaled)
y_pred = np.where(y_log > 0.5, 1, 0)

63/63 [==============================] - 0s 2ms/step


In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test, y_pred)

0.802